services:
  frontend:
    image: 14790897/frontend-handwriting:latest
    ports:
      - "2345:80"
    depends_on:
      - backend
    cpu_count: 1
    cpu_quota: 50000
    cpu_period: 100000
    mem_limit: 800m
    memswap_limit: 1600m


  backend:
    image: 14790897/backend-handwriting:latest
    ports:
      - "127.0.0.1:5005:5005"
    environment:
      - FONT_ASSETS_DIR=/app/font_assets_host
      - FONT_ASSETS_BUNDLED_DIR=/app/font_assets
    volumes:
      - ./ttf_files:/app/font_assets_host
      - ./logs:/app/logs
    cpu_count: 1
    cpu_quota: 80000
    cpu_period: 100000
    mem_limit: 1500m
    memswap_limit: 4000m
 

