blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ ç”µæŠ¥è®¨è®ºç¾¤ç»„
    url: https://t.me/+zFImOziSNullOTE1
    about: åŠ å…¥æˆ‘ä»¬çš„ Telegram ç¾¤ç»„è¿›è¡Œè®¨è®ºå’Œè·å–å¸®åŠ©
  - name: ğŸ“– é¡¹ç›®æ–‡æ¡£
    url: https://github.com/14790897/handwriting-web/blob/master/README.md
    about: æŸ¥çœ‹é¡¹ç›®æ–‡æ¡£å’Œä½¿ç”¨è¯´æ˜
